# SOMI Signal Test Configuration
# 테스트 전용 설정 - 기존 시스템과 간섭 없음

# Server settings (테스트용)
server:
  host: "localhost"
  port: 8081  # 다른 포트 사용으로 기존 시스템과 충돌 방지
  timeout: "30s"

# Upbit monitoring settings (테스트에서는 사용하지 않음)
upbit:
  enabled: false  # 테스트에서는 가짜 시그널 사용
  api_url: "https://api-manager.upbit.com/api/v1/announcements?os=web&page=1&per_page=20&category=trade"
  poll_interval: "5s"
  timeout: "10s"
  user_agent: "SOMI-Test-v1.0"

# Exchange WebSocket configurations (기존과 동일)
exchanges:
  binance:
    enabled: true
    spot_endpoint: "wss://stream.binance.com:9443/ws"
    futures_endpoint: "wss://fstream.binance.com/ws"
    max_symbols_per_connection: 100
    retry_cooldown: "5s"
    max_retries: 10
    connection_timeout: "30s"
    read_timeout: "30s"
    write_timeout: "10s"

  bybit:
    enabled: true
    spot_endpoint: "wss://stream.bybit.com/v5/public/spot"
    futures_endpoint: "wss://stream.bybit.com/v5/public/linear"
    max_symbols_per_connection: 50
    retry_cooldown: "5s"
    max_retries: 10
    connection_timeout: "30s"
    read_timeout: "30s"
    write_timeout: "10s"

  kucoin:
    enabled: true
    spot_endpoint: "wss://ws-api.kucoin.com/endpoint"
    futures_endpoint: "wss://ws-api-futures.kucoin.com/endpoint"
    max_symbols_per_connection: 100
    retry_cooldown: "5s"
    max_retries: 10
    connection_timeout: "30s"
    read_timeout: "30s"
    write_timeout: "10s"

  okx:
    enabled: true
    spot_endpoint: "wss://ws.okx.com:8443/ws/v5/public"
    futures_endpoint: "wss://ws.okx.com:8443/ws/v5/public"
    max_symbols_per_connection: 100
    retry_cooldown: "5s"
    max_retries: 10
    connection_timeout: "30s"
    read_timeout: "30s"
    write_timeout: "10s"

  gate:
    enabled: true
    spot_endpoint: "wss://api.gateio.ws/ws/v4/"
    futures_endpoint: "wss://fx-ws.gateio.ws/v4/ws/usdt"
    max_symbols_per_connection: 100
    retry_cooldown: "5s"
    max_retries: 10
    connection_timeout: "30s"
    read_timeout: "30s"
    write_timeout: "10s"

  phemex:
    enabled: true
    spot_endpoint: "wss://ws.phemex.com"
    futures_endpoint: "wss://ws.phemex.com"
    max_symbols_per_connection: 20
    retry_cooldown: "5s"
    max_retries: 10
    connection_timeout: "30s"
    read_timeout: "30s"
    write_timeout: "10s"

# Storage settings (테스트 전용 디렉토리)
storage:
  enabled: true
  data_dir: "./cmd/test-somi-signal/data"  # 테스트 전용 데이터 디렉토리
  raw_data_enabled: true
  refined_enabled: true
  compression: false
  retention_days: 1  # 테스트 데이터는 1일만 보관
  max_file_size: "100MB"
  backup_enabled: false  # 테스트에서는 백업 비활성화
  backup_interval: "24h"

# Analysis settings
analysis:
  pump_threshold: 3.0  # 3% price increase threshold
  time_window_seconds: 1
  min_volume_ratio: 2.0

# Collection timing settings (테스트 최적화)
collection:
  pre_trigger_duration: "20s"    # -20초부터 수집
  collection_duration: "20s"     # +20초까지 수집 (총 40초)
  post_analysis_delay: "2s"      # 분석 전 대기시간

# System timing settings (테스트 최적화)
system:
  shutdown_timeout: "10s"        # 빠른 종료
  status_report_interval: "30s"  # 더 자주 상태 보고
  auto_save_interval: "1m"       # 자주 저장
  pool_startup_delay: "200ms"    # 빠른 시작

# Connection timing settings
connection:
  default_ping_interval: "25s"
  default_connection_timeout: "30s"
  default_retry_delay: "1s"
  batch_processing_delay: "100ms"  # 빠른 처리
  api_rate_limit_delay: "50ms"     # 테스트용 짧은 지연